trigger:
- master

stages:
  - stage: Build
    jobs:
    - job: Build
      pool: selfAgents 
      steps:
      - task: CmdLine@2
        displayName: Install ZIP and Unzip utility
        inputs:
          script: 'sudo apt update -y && sudo apt install zip -y && sudo apt install unzip -y'
      - task: TerraformInstaller@1
        displayName: Terraform Install
        inputs:
          terraformVersion: 'latest'    
      - task: TerraformTaskV4@4
        displayName: TF Init
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: 'Free Trial(5635a262-c054-46d0-9904-c079ed441435)'
          backendAzureRmResourceGroupName: 'supportRG'
          backendAzureRmStorageAccountName: 'tfstatestoreacc01'
          backendAzureRmContainerName: 'tfstateblob'
          backendAzureRmKey: 'mediawiki.terraform.tfstate'
      - task: TerraformTaskV4@4
        displayName: Tf Fmt
        inputs:
          provider: 'azurerm'
          command: 'custom'
          customCommand: 'fmt'
          outputTo: 'console'
          environmentServiceNameAzureRM: 'Free Trial(5635a262-c054-46d0-9904-c079ed441435)'

      - task: TerraformTaskV4@4
        displayName: Tf validate 
        inputs:
          provider: 'azurerm'
          command: 'validate'
      - task: TerraformTaskV4@4
        displayName: Tf plan
        inputs:
          provider: 'azurerm'
          command: 'plan'
          commandOptions: '-out $(Build.SourcesDirectory)/tfplanfile'
          environmentServiceNameAzureRM: 'Free Trial(5635a262-c054-46d0-9904-c079ed441435)'
      - task: ArchiveFiles@2
        displayName: Archive the files
        inputs:
          rootFolderOrFile: '$(Build.SourcesDirectory)/'
          includeRootFolder: false
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
          replaceExistingArchive: true
      - task: PublishBuildArtifacts@1
        displayName: Publish the artifact
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: '$(Build.BuildId)-Build'
          publishLocation: 'Container'